# Generated by Django 5.2.4 on 2025-07-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["id"],
                "permissions": [("can_block_user", "Can block user"), ("can_unlock_user", "Can unlock user")],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
