# Generated by Django 5.2.4 on 2025-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="server_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
