# Generated by Django 5.2.4 on 2025-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="finished_at",
            field=models.DateTimeField(),
        ),
    ]
